data:
  datalist_dir: /gpfs/data/geraslab/Yanqi/image-to-text/datalist/mammo_jp_09082022_withreport_meta_datalist_09182023.pkl
  datalist_prefix: /gpfs/data/geraslab/Yanqi/image-to-text/mammo_data
  img_dir: /gpfs/data/geraslab/jp4989/data/2021.07.16.combined_ffdm_cropped
  segmentation_dir: /gpfs/data/geraslab/jp4989/extract_dbt_segmentation/2022.06.12.cropped_segmentation
  batch_size: 4
  label_type: abnormality
  pin_memory: true
  num_workers: 6
  # Thomas said it should be at least about 5-10x your batch size; beyond that,
  # the differences become academic.
  shuffle_buffer: 10000
  seed: ${train.seed}
  mode: contrastive
  img_aug:
    deit_aug: true
    img_size: [736, 480]
    img_scale: [0.08, 1.0]
    interpolation: bilinear
    color_jitter: 0.4
    auto_augment: 'rand-m9-mstd0.5-inc1'
    re_prob: 0.25
    re_mode: 'pixel'
    re_count: 1
  text_aug:
    max_seq_len: 77
    multi_label: 0
    word_type: 'noun'

train:
  slurm: false
  start_epoch: 0
  epochs: 30
  warmup_epochs: 2
  base_lr: 1.6e-3
  weight_decay: 0.05
  warmup_lr: 1e-7
  min_lr: 1e-7
  clip_grad: 5.0
  accumulation_steps: 0
  amp_opt_level: O1
  seed: 0

  lr_scheduler:
    name: cosine

  optimizer:
    name: adamw
    eps: 1e-8
    betas: [0.9, 0.999]

evaluate:
  eval_only: false
  eval_freq: 1
  task:
    - cls
  cls:
    save_best: true
    template: subset
  seg:
    save_best: true
    cfg: /gpfs/data/geraslab/Yanqi/image-to-text/mammo-groupvit/segmentation/configs/_base_/datasets/breast_cancer.py
    template: simple
    opts: []

checkpoint:
  auto_resume: true
  resume: ''
  freq: 1
  max_kept: -1
  save_freq: 5


model_name: '' # display name in the logger
output: ???
tag: default
print_freq: 10
seed: 0
wandb: false
local_rank: ???
vis: []
