_base_: 'default_breast.yml'
data: 
  datalist_dir: /gpfs/data/geraslab/Yanqi/image-to-text/datalist/mammo_jp_09082022_withreport_meta_datalist_09182023.pkl
  pos_to_neg_ratio: 3
  num_positives: 60000
  img_aug:
    img_size: [736, 480]
  mode: simple-contras
model:
  type: MultiLabelContrastive
  img_encoder:
    type: GroupViT
    img_size: ${data.img_aug.img_size} 
    embed_dim: 384
    patch_size: 16
    num_heads: [6, 6, 6]
    depths: [6, 3, 3]
    num_group_tokens: [64, 8, 0]
    num_output_groups: [64, 8]
    drop_rate: 0.0
    drop_path_rate: 0.1
  text_encoder:
    type: TextTransformer
    context_length: 77
    width: 256
    layers: 12
    vocab_size: 49408
  contrast_temperature: 0.07
  proj_num_layers: 2
  output_dim: 256
  multi_label: ${data.text_aug.multi_label} # multi_label=0 is better for RedCap
  fully_supervised: false

evaluate:
  task:
    - cls
    - seg
checkpoint:
  auto_resume: true
  save_freq: 5
  resume: '/gpfs/data/geraslab/Yanqi/image-to-text/pretrained_weights/group_vit_gcc_redcap_30e-3dd09a76.pth'
train:
  epochs: 30
  base_lr: 1e-4
  clip_grad: 1
  warmup_lr: 1e-7
  min_lr: 1e-7