_base_: 'default_breast.yml'
data:
  datalist_dir: /gpfs/data/geraslab/Yanqi/image-to-text/datalist/mammo_jp_09082022_withreport_meta_datalist_09292023_clean.pkl
  pos_to_neg_ratio: 1
  num_positives: 120000
  img_aug:
    img_size: [736, 480]
  mode: supervised
model:
  type: MultiLabelContrastive
  img_encoder: 'resnet-torchvision'
    # type: ModifiedResNet
    # layers: [3, 4, 6, 3]
    # output_dim: 256
    # heads: 32
    # input_resolution: ${data.img_aug.img_size} 
    # width: 64
  text_encoder:
    type: TextTransformer
    context_length: 77
    width: 256
    layers: 12
    vocab_size: 49408
  contrast_temperature: 0.07
  proj_num_layers: 0
  output_dim: 256
  multi_label: ${data.text_aug.multi_label} # multi_label=0 is better for RedCap
  label_type: ${data.label_type}
  fully_supervised: true
  img_encoder_checkpoint: /gpfs/data/geraslab/Yanqi/image-to-text/pretrained_weights/RN50.pt
evaluate:
  task:
    -cls
checkpoint:
  auto_resume: false
  save_freq: 5
train:
  epochs: 30
  base_lr: 1e-3
  weight_decay: 0.05
  clip_grad: 1.0
  


