_base_: 'default_breast_test.yml'
data:
  datalist_dir: /gpfs/data/geraslab/Yanqi/image-to-text/datalist/mammo_jp_09082022_withreport_meta_datalist_short.pkl
  batch_size: 10

model:
  type: MultiLabelContrastive
  img_encoder:
    type: VisionTransformer
    input_resolution: 224 
    patch_size: 32
    width: 768
    layers: 12
    heads: 12
    output_dim: 256
  text_encoder:
    type: TextTransformer
    context_length: 77
    width: 256
    layers: 12
    vocab_size: 49408
  contrast_temperature: 0.07
  proj_num_layers: 0
  output_dim: 256
  multi_label: ${data.text_aug.multi_label} # multi_label=0 is better for RedCap
  fully_supervised: true

evaluate:
  task:
    - cls
checkpoint:
  auto_resume: false
  save_freq: 25
train:
  epochs: 50
  base_lr: 5e-3